---
version: "3"
services:
 devopsdb:
   image: dbimage
   ports:
     - "3306:3306"
   deploy:
      replicas: 1

 application:
   image: appimage
   ports:
     - "1234:8080"
   depends_on:
     - "devopsdb"
   deploy:
      replicas: 3
